create extension pgcrypto;

create unique index user_email_inx on users(user_email);


create table users (
  user_id int generated by default as identity primary key,
  user_name varchar(256) not null,
  user_email varchar(512) not null,
  is_active boolean default false,
  password varchar(256) not null,
  created_at timestamptz default current_timestamp
);

insert into users (user_name, user_login, user_email, password) values ('John', 'johndoe', 'eustoz@admin.uz',  crypt('123', gen_salt('bf')));

create table messages (
  message_id int generated by default as identity primary key,
  message_text varchar,
  message_file varchar(256),
  is_read boolean default false, 
  author_id int not null references users(user_id),
  user_id int not null references users(user_id),
  created_at timestamptz default current_timestamp
);

insert into messages (message_text, message_file, author_id, user_id) values ('Jahongir yaxshimisan, xorma', 'https://www.picng.com/upload/mario/png_mario_75809.png', 3, 4);
